# Generated by Django 4.2.11 on 2024-04-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app_jo', '0002_alter_user_clefgeneree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ClefGeneree',
            field=models.CharField(default='5bd25e30692132a6ad6c408db0375afe', max_length=50),
        ),
    ]
