# Generated by Django 5.0.3 on 2024-03-19 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competitions',
            fields=[
                ('pk_typ_competition', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Dates_commandes',
            fields=[
                ('pk_date', models.DateTimeField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Dates_Competions',
            fields=[
                ('pk_date_competition', models.DateTimeField(primary_key=True, serialize=False)),
                ('date_debut', models.DateTimeField()),
                ('Dates_fin', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='lieu_des_competions',
            fields=[
                ('pk_lieu', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=250)),
                ('Ville', models.CharField(max_length=50)),
                ('Capacite', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='list_competition',
            fields=[
                ('pk_list_competition', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('pk_Offre', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=250)),
                ('NombrePersonnes', models.IntegerField()),
                ('Prix', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('pk_Utilisateur', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=150)),
                ('Prenom', models.CharField(max_length=150)),
                ('AdresseEmail', models.EmailField(max_length=50, unique=True)),
                ('MotDePasse', models.CharField(max_length=250)),
                ('Date_de_Naissance', models.DateField()),
                ('ClefGeneree', models.CharField(default='a4f7e976b661fc8487074c17d6185414', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Billet',
            fields=[
                ('pk_Billet', models.AutoField(primary_key=True, serialize=False)),
                ('Cledebilletelectroniquesecurisee', models.CharField(max_length=50)),
                ('ClefBillet', models.CharField(max_length=250)),
                ('ClefSecurite', models.CharField(max_length=250)),
                ('pk_typ_competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app_jo.competitions')),
            ],
        ),
        migrations.AddField(
            model_name='competitions',
            name='pk_date_competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app_jo.dates_competions'),
        ),
        migrations.AddField(
            model_name='competitions',
            name='pk_lieu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app_jo.lieu_des_competions'),
        ),
        migrations.AddField(
            model_name='competitions',
            name='pk_list_competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app_jo.list_competition'),
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('pk_Commande', models.AutoField(primary_key=True, serialize=False)),
                ('quantite', models.IntegerField()),
                ('MontantTotal', models.FloatField()),
                ('pk_date', models.DateTimeField(auto_now_add=True)),
                ('pk_Billet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app_jo.billet')),
                ('pk_Competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app_jo.competitions')),
                ('pk_Offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app_jo.offre')),
                ('pk_Utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app_jo.utilisateur')),
            ],
        ),
    ]
