# Generated by Django 5.0.3 on 2024-03-20 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitions',
            fields=[
                ('pk_typ_competition', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Dates_commandes',
            fields=[
                ('pk_date', models.DateTimeField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Dates_Competions',
            fields=[
                ('pk_date_competition', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('Remises_de_medailles', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Lieu_des_competions',
            fields=[
                ('pk_lieu', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=250)),
                ('Ville', models.CharField(max_length=50)),
                ('Capacite', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='List_competition',
            fields=[
                ('pk_list_competition', models.CharField(max_length=150, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ODS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(max_length=250)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('lieu', models.CharField(max_length=250)),
                ('capacite', models.BigIntegerField()),
                ('remises_de_medailles', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('pk_Offre', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=250)),
                ('NombrePersonnes', models.IntegerField()),
                ('Prix', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('pk_Utilisateur', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=150)),
                ('Prenom', models.CharField(max_length=150)),
                ('AdresseEmail', models.EmailField(max_length=50, unique=True)),
                ('MotDePasse', models.CharField(max_length=250)),
                ('Date_de_Naissance', models.DateField()),
                ('ClefGeneree', models.CharField(default='de96c7cd97b2dbb6d682009e6b9b8276', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Billet',
            fields=[
                ('pk_Billet', models.AutoField(primary_key=True, serialize=False)),
                ('Cledebilletelectroniquesecurisee', models.CharField(max_length=50)),
                ('ClefBillet', models.CharField(max_length=250)),
                ('ClefSecurite', models.CharField(max_length=250)),
                ('pk_typ_competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app_jo.competitions')),
            ],
        ),
        migrations.AddField(
            model_name='competitions',
            name='pk_date_competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app_jo.dates_competions'),
        ),
        migrations.AddField(
            model_name='competitions',
            name='pk_lieu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app_jo.lieu_des_competions'),
        ),
        migrations.AddField(
            model_name='lieu_des_competions',
            name='Discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app_jo.list_competition'),
        ),
        migrations.AddField(
            model_name='dates_competions',
            name='pk_list_competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app_jo.list_competition'),
        ),
        migrations.AddField(
            model_name='competitions',
            name='pk_list_competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app_jo.list_competition'),
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('pk_Commande', models.AutoField(primary_key=True, serialize=False)),
                ('quantite', models.IntegerField()),
                ('MontantTotal', models.FloatField()),
                ('pk_date', models.DateTimeField(auto_now_add=True)),
                ('pk_Billet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app_jo.billet')),
                ('pk_Utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pk_Competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app_jo.competitions')),
                ('pk_Offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app_jo.offre')),
            ],
        ),
    ]
