# Generated by Django 5.0.3 on 2024-03-30 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app_jo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competitions',
            old_name='pk_lieu_id',
            new_name='pk_lieu',
        ),
        migrations.RenameField(
            model_name='dates_competions',
            old_name='pk_list_competition_id',
            new_name='pk_list_competition',
        ),
        migrations.AlterField(
            model_name='user',
            name='ClefGeneree',
            field=models.CharField(default='65a757cd93f2cfc05fec27d41670b0ad', max_length=50),
        ),
    ]
