# Generated by Django 5.0.3 on 2024-03-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app_jo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ClefGeneree',
            field=models.CharField(default='b4666012c62702036272ed1b77f8ded5', max_length=50),
        ),
    ]
