# Generated by Django 5.0.3 on 2024-04-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app_jo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dates_competions',
            name='pk_date_competition',
            field=models.CharField(max_length=600, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='ClefGeneree',
            field=models.CharField(default='5f083d82a657150eb3b90f9927ccf9da', max_length=50),
        ),
    ]
