# Generated by Django 5.0.3 on 2024-03-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app_jo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='pk_Offre',
            field=models.CharField(max_length=300, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='ClefGeneree',
            field=models.CharField(default='0c171689fbd87e24a5e2cfadef22ccf7', max_length=50),
        ),
    ]
