# Generated by Django 5.0.3 on 2024-04-08 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app_jo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billet',
            name='ClefUtilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='ClefGeneree',
            field=models.CharField(default='923286247fc06ba79688a526caed308f', max_length=50),
        ),
    ]
