# Generated by Django 4.0.10 on 2024-04-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app_jo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ClefGeneree',
            field=models.CharField(default='f82477e153adde337e1048a9648c1a11', max_length=50),
        ),
    ]
