# Generated by Django 5.0.3 on 2024-04-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app_jo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ClefGeneree',
            field=models.CharField(default='d7d73a0d1237c148be791c5b1a8d145a', max_length=50),
        ),
    ]
