# Generated by Django 5.0.3 on 2024-03-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app_jo', '0002_rename_pk_lieu_id_competitions_pk_lieu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ClefGeneree',
            field=models.CharField(default='7cb59f2726cfba9eca7765df37536dab', max_length=50),
        ),
    ]
