# Generated by Django 5.0.3 on 2024-04-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app_jo', '0002_alter_code_number_alter_user_clefgeneree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='est_validee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='ClefGeneree',
            field=models.CharField(default='202c20cf848e74a23e4c96fc94efea5e', max_length=50),
        ),
    ]
