# Generated by Django 5.0.3 on 2024-03-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app_jo', '0002_alter_offre_pk_offre_alter_user_clefgeneree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='pk_Offre',
            field=models.CharField(max_length=2000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='ClefGeneree',
            field=models.CharField(default='0d0aaf327c919a264f10f56f045a4bf1', max_length=50),
        ),
    ]
