# Generated by Django 5.0.3 on 2024-04-10 22:20

import my_app_jo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app_jo', '0002_alter_dates_competions_pk_date_competition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_competition',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=my_app_jo.models.get_competition_image_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='ClefGeneree',
            field=models.CharField(default='087493844c368afd96c940b185f38567', max_length=50),
        ),
    ]
