# Generated by Django 5.0.3 on 2024-04-16 16:38

import my_app_jo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app_jo', '0002_competitions_image_alter_list_competition_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitions',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=my_app_jo.models.get_competition_image_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='ClefGeneree',
            field=models.CharField(default='3929a5e2699ddbae1fb480019de8d242', max_length=50),
        ),
    ]
