# Generated by Django 5.0.3 on 2024-03-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app_jo', '0003_alter_offre_pk_offre_alter_user_clefgeneree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ClefGeneree',
            field=models.CharField(default='e107026fcc33225f49cb6a26de83035d', max_length=50),
        ),
    ]
