# Generated by Django 5.0.3 on 2024-04-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app_jo', '0003_alter_billet_clefutilisateur_alter_user_clefgeneree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billet',
            name='date_valide',
        ),
        migrations.AlterField(
            model_name='user',
            name='ClefGeneree',
            field=models.CharField(default='832929f1a3bfe702a9fafecde17fad31', max_length=50),
        ),
    ]
