# Generated by Django 5.0.3 on 2024-04-16 17:54

import my_app_jo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app_jo', '0003_alter_competitions_image_alter_user_clefgeneree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitions',
            name='image',
            field=models.ImageField(blank=True, max_length=455, null=True, upload_to=my_app_jo.models.get_competition_image_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='ClefGeneree',
            field=models.CharField(default='d538225ff248c566989ea87a047e04e1', max_length=50),
        ),
    ]
