# Generated by Django 5.0.3 on 2024-04-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app_jo', '0004_remove_billet_date_valide_alter_user_clefgeneree'),
    ]

    operations = [
        migrations.AddField(
            model_name='billet',
            name='date_valide',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ClefGeneree',
            field=models.CharField(default='39a9cafceabc5885afbfc1b757e0109e', max_length=50),
        ),
    ]
