# Generated by Django 5.0.3 on 2024-04-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app_jo', '0005_alter_user_clefgeneree'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dates_commandes',
        ),
        migrations.AlterField(
            model_name='user',
            name='ClefGeneree',
            field=models.CharField(default='615afcae24734cfe71908e9408f24b54', max_length=50),
        ),
    ]
